services:
  redis:
    container_name: redis
    restart: always
    image: redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_USER: ${REDIS_USER}
    networks:
      - redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
networks:
  redis:
    name: redis
volumes:
  redis:
    name: redis